/*
 * This source file was generated by the Gradle 'init' task
 */
package app.src.test.java.cn.naipu.MiraiTris;

import org.junit.Test;
import static org.junit.Assert.*;
import app.src.main.java.cn.naipu.MiraiTris.App;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
